#!/usr/bin/env bash
#Install nginx web server /Redirection
apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/EslamAlawamy permanent;/" /etc/nginx/sites-available/default
service nginx start
